# Generated by Django 5.2.5 on 2025-08-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
