# Generated by Django 5.2.5 on 2025-08-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_image_article_image_url_country_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف التصنيف'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='صورة التصنيف'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط صورة التصنيف'),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='countries/', verbose_name='صورة الدولة'),
        ),
        migrations.AlterField(
            model_name='country',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط صورة الدولة'),
        ),
    ]
